-- =============================================================================
-- FILE : 02_reorg_procedure.sql
-- Compile once. Run via 03_run.sql each downtime.
--
-- This procedure ONLY does work and writes status to REORG_TRACKER.
-- HTML report is generated by 03_run.sql using SQL*Plus MARKUP HTML ON.
-- This avoids the DBMS_OUTPUT buffer hang issue entirely.
-- =============================================================================
SET DEFINE OFF

CREATE OR REPLACE PROCEDURE SYS.REORG_TABLE (
    p_schema  IN VARCHAR2,
    p_table   IN VARCHAR2
)
AS
    v_schema      VARCHAR2(30)   := UPPER(TRIM(p_schema));
    v_table       VARCHAR2(128)  := UPPER(TRIM(p_table));
    v_seq         NUMBER         := 0;
    v_step_start  TIMESTAMP;
    v_elapsed     NUMBER;
    v_part_count  NUMBER;
    v_sub_count   NUMBER;
    v_lob_count   NUMBER;
    v_lobp_count  NUMBER;
    v_err         VARCHAR2(4000);

    -- =========================================================================
    -- log_alert : write to DB alert log immediately (visible even if proc hangs)
    -- =========================================================================
    PROCEDURE log_alert (p_msg IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'BEGIN sys.DBMS_SYSTEM.ksdwrt(2,:m); END;'
        USING SUBSTRB('[REORG]['||v_schema||'.'||v_table||'] '||p_msg, 1, 2000);
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    -- =========================================================================
    -- add_step : insert one PENDING row, skip silently if already exists
    -- =========================================================================
    PROCEDURE add_step (
        p_seq  IN NUMBER,   p_type IN VARCHAR2,
        p_tgt1 IN VARCHAR2, p_tgt2 IN VARCHAR2,
        p_tbs  IN VARCHAR2, p_ddl  IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO SYS.REORG_TRACKER
            (schema_name, table_name, step_seq, step_type,
             step_target, step_target2, tablespace_name, ddl_statement, status)
        SELECT v_schema, v_table, p_seq, p_type,
               p_tgt1, p_tgt2, p_tbs, p_ddl, 'PENDING'
        FROM DUAL
        WHERE NOT EXISTS (
            SELECT 1 FROM SYS.REORG_TRACKER
            WHERE schema_name = v_schema
              AND table_name  = v_table
              AND step_seq    = p_seq
        );
    END;

BEGIN
    -- =========================================================================
    -- PHASE 0 : SESSION SETTINGS
    -- =========================================================================
    EXECUTE IMMEDIATE 'ALTER SESSION FORCE PARALLEL QUERY PARALLEL 16';
    EXECUTE IMMEDIATE 'ALTER SESSION FORCE PARALLEL DDL   PARALLEL 16';

    log_alert('START');

    -- =========================================================================
    -- PHASE 1 : SEED
    -- Inspect table structure and register every step as PENDING.
    -- On resume runs, existing rows are skipped. DONE rows never overwritten.
    -- =========================================================================
    SELECT COUNT(*) INTO v_part_count  FROM dba_tab_partitions   WHERE table_owner=v_schema AND table_name=v_table;
    SELECT COUNT(*) INTO v_sub_count   FROM dba_tab_subpartitions WHERE table_owner=v_schema AND table_name=v_table;
    SELECT COUNT(*) INTO v_lob_count   FROM dba_lobs              WHERE owner=v_schema AND table_name=v_table AND partitioned='NO';
    SELECT COUNT(*) INTO v_lobp_count  FROM dba_lob_partitions    WHERE table_owner=v_schema AND table_name=v_table;

    log_alert('Structure: parts='||v_part_count||' subparts='||v_sub_count
              ||' lobs='||v_lob_count||' lob_parts='||v_lobp_count);

    -- SEQ 1000s : TABLE / PARTITION / SUBPARTITION moves
    v_seq := 1000;

    -- Non-partitioned full table move
    IF v_part_count = 0 THEN
        add_step(v_seq, 'MOVE_TABLE', NULL, NULL, NULL,
            'ALTER TABLE '||v_schema||'.'||v_table||' MOVE PARALLEL 16');
        v_seq := v_seq + 1;
    END IF;

    -- Partitions only (no subpartitions)
    IF v_part_count > 0 AND v_sub_count = 0 THEN
        FOR r IN (
            SELECT partition_name FROM dba_tab_partitions
            WHERE table_owner=v_schema AND table_name=v_table
            ORDER BY partition_position
        ) LOOP
            add_step(v_seq, 'MOVE_PARTITION', r.partition_name, NULL, NULL,
                'ALTER TABLE '||v_schema||'.'||v_table||
                ' MOVE PARTITION '||r.partition_name||' PARALLEL 16');
            v_seq := v_seq + 1;
        END LOOP;
    END IF;

    -- Subpartitions (composite partitioned)
    IF v_sub_count > 0 THEN
        FOR r IN (
            SELECT subpartition_name, partition_name, subpartition_position
            FROM dba_tab_subpartitions
            WHERE table_owner=v_schema AND table_name=v_table
            ORDER BY partition_name, subpartition_position
        ) LOOP
            add_step(v_seq, 'MOVE_SUBPART', r.subpartition_name, r.partition_name, NULL,
                'ALTER TABLE '||v_schema||'.'||v_table||
                ' MOVE SUBPARTITION '||r.subpartition_name);
            v_seq := v_seq + 1;
        END LOOP;
    END IF;

    -- SEQ 2000s : LOB moves
    v_seq := 2000;

    -- Non-partitioned LOBs
    IF v_lob_count > 0 THEN
        FOR r IN (
            SELECT column_name, tablespace_name FROM dba_lobs
            WHERE owner=v_schema AND table_name=v_table AND partitioned='NO'
            ORDER BY column_name
        ) LOOP
            add_step(v_seq, 'MOVE_LOB', NULL, r.column_name, r.tablespace_name,
                'ALTER TABLE '||v_schema||'.'||v_table||
                ' MOVE LOB ('||r.column_name||') STORE AS (TABLESPACE '||r.tablespace_name||')');
            v_seq := v_seq + 1;
        END LOOP;
    END IF;

    -- LOB partitions
    IF v_lobp_count > 0 THEN
        FOR r IN (
            SELECT p.partition_name, l.column_name, l.tablespace_name
            FROM dba_lob_partitions l
            JOIN dba_tab_partitions p
              ON l.table_owner=p.table_owner AND l.table_name=p.table_name
             AND l.partition_name=p.partition_name
            WHERE l.table_owner=v_schema AND l.table_name=v_table
              AND l.tablespace_name IS NOT NULL
            ORDER BY p.partition_position, l.column_name
        ) LOOP
            add_step(v_seq, 'MOVE_LOB_PART', r.partition_name, r.column_name, r.tablespace_name,
                'ALTER TABLE '||v_schema||'.'||v_table||
                ' MOVE PARTITION '||r.partition_name||
                ' LOB ('||r.column_name||') STORE AS (TABLESPACE '||r.tablespace_name||')');
            v_seq := v_seq + 1;
        END LOOP;
    END IF;

    -- SEQ 3000s : Index rebuilds
    v_seq := 3000;

    -- Non-partitioned regular indexes
    FOR r IN (
        SELECT owner, index_name FROM dba_indexes
        WHERE owner=v_schema AND table_name=v_table
          AND partitioned='NO' AND index_type<>'LOB'
        ORDER BY index_name
    ) LOOP
        add_step(v_seq, 'REBUILD_IDX', r.index_name, NULL, NULL,
            'ALTER INDEX '||r.owner||'.'||r.index_name||' REBUILD PARALLEL 16');
        v_seq := v_seq + 1;
    END LOOP;

    -- Index partitions
    FOR r IN (
        SELECT b.index_owner, b.index_name, b.partition_name
        FROM dba_indexes a JOIN dba_ind_partitions b
          ON a.owner=b.index_owner AND a.index_name=b.index_name
        WHERE a.owner=v_schema AND a.table_name=v_table AND a.index_type<>'LOB'
        ORDER BY b.index_name, b.partition_position
    ) LOOP
        add_step(v_seq, 'REBUILD_IDX_PART', r.index_name, r.partition_name, NULL,
            'ALTER INDEX '||r.index_owner||'.'||r.index_name||
            ' REBUILD PARTITION '||r.partition_name||' PARALLEL 16');
        v_seq := v_seq + 1;
    END LOOP;

    -- Index subpartitions
    FOR r IN (
        SELECT b.index_owner, b.index_name, b.subpartition_name
        FROM dba_indexes a JOIN dba_ind_subpartitions b
          ON a.owner=b.index_owner AND a.index_name=b.index_name
        WHERE a.owner=v_schema AND a.table_name=v_table AND a.index_type<>'LOB'
        ORDER BY b.index_name, b.subpartition_name
    ) LOOP
        add_step(v_seq, 'REBUILD_IDX_SP', r.index_name, r.subpartition_name, NULL,
            'ALTER INDEX '||r.index_owner||'.'||r.index_name||
            ' REBUILD SUBPARTITION '||r.subpartition_name||' PARALLEL 16');
        v_seq := v_seq + 1;
    END LOOP;

    -- Non-partitioned LOB indexes
    FOR r IN (
        SELECT owner, index_name FROM dba_indexes
        WHERE table_owner=v_schema AND table_name=v_table
          AND index_type='LOB' AND partitioned='NO'
        ORDER BY index_name
    ) LOOP
        add_step(v_seq, 'REBUILD_LOB_IDX', r.index_name, NULL, NULL,
            'ALTER INDEX '||r.owner||'.'||r.index_name||' REBUILD');
        v_seq := v_seq + 1;
    END LOOP;

    -- LOB index partitions
    FOR r IN (
        SELECT b.index_owner, b.index_name, b.partition_name
        FROM dba_indexes a JOIN dba_ind_partitions b
          ON a.owner=b.index_owner AND a.index_name=b.index_name
        WHERE a.table_owner=v_schema AND a.table_name=v_table AND a.index_type='LOB'
        ORDER BY b.index_name, b.partition_position
    ) LOOP
        add_step(v_seq, 'REBUILD_LOB_PART', r.index_name, r.partition_name, NULL,
            'ALTER INDEX '||r.index_owner||'.'||r.index_name||
            ' REBUILD PARTITION '||r.partition_name);
        v_seq := v_seq + 1;
    END LOOP;

    COMMIT;
    log_alert('SEED DONE - '||v_seq||' steps registered');

    -- =========================================================================
    -- PHASE 2 : RECOVER
    -- Any step stuck as RUNNING from a killed previous session -> reset to PENDING
    -- =========================================================================
    UPDATE SYS.REORG_TRACKER
       SET status    = 'PENDING',
           error_msg = 'Reset from RUNNING - prev session killed '||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS')
     WHERE schema_name = v_schema
       AND table_name  = v_table
       AND status      = 'RUNNING';

    IF SQL%ROWCOUNT > 0 THEN
        log_alert('RECOVERED '||SQL%ROWCOUNT||' RUNNING steps -> PENDING');
    END IF;
    COMMIT;

    -- =========================================================================
    -- PHASE 3 : EXECUTE
    -- Loop PENDING/FAILED in step_seq order.
    -- DONE rows excluded from cursor -> never re-executed.
    -- Mark RUNNING + COMMIT before DDL so a killed session leaves a breadcrumb.
    -- Mark DONE/FAILED + COMMIT after each step.
    -- =========================================================================
    FOR step IN (
        SELECT step_seq, step_type, step_target, step_target2, ddl_statement
        FROM SYS.REORG_TRACKER
        WHERE schema_name = v_schema
          AND table_name  = v_table
          AND status NOT IN ('DONE','SKIPPED')
        ORDER BY step_seq
    ) LOOP

        v_step_start := SYSTIMESTAMP;
        log_alert('RUN ['||step.step_seq||'] '||step.step_type||
                  ' -> '||NVL(step.step_target, v_table));

        -- Mark RUNNING before DDL fires
        UPDATE SYS.REORG_TRACKER
           SET status     = 'RUNNING',
               started_at = v_step_start,
               error_msg  = NULL
         WHERE schema_name = v_schema
           AND table_name  = v_table
           AND step_seq    = step.step_seq;
        COMMIT;

        BEGIN
            EXECUTE IMMEDIATE step.ddl_statement;

            v_elapsed := ROUND(
                EXTRACT(HOUR   FROM (SYSTIMESTAMP-v_step_start))*3600 +
                EXTRACT(MINUTE FROM (SYSTIMESTAMP-v_step_start))*60   +
                EXTRACT(SECOND FROM (SYSTIMESTAMP-v_step_start)), 1);

            UPDATE SYS.REORG_TRACKER
               SET status       = 'DONE',
                   completed_at = SYSTIMESTAMP,
                   elapsed_secs = v_elapsed
             WHERE schema_name = v_schema
               AND table_name  = v_table
               AND step_seq    = step.step_seq;
            COMMIT;

            log_alert('DONE ['||step.step_seq||'] '||v_elapsed||'s');

            -- After each SUBPARTITION move rebuild any UNUSABLE index subparts immediately
            IF step.step_type = 'MOVE_SUBPART' THEN
                FOR ix IN (
                    SELECT i.index_owner, i.index_name, i.subpartition_name
                    FROM dba_ind_subpartitions i
                    JOIN dba_indexes d ON d.owner=i.index_owner AND d.index_name=i.index_name
                    WHERE i.status    = 'UNUSABLE'
                      AND d.table_owner = v_schema
                      AND d.table_name  = v_table
                      AND d.index_type <> 'LOB'
                ) LOOP
                    BEGIN
                        EXECUTE IMMEDIATE
                            'ALTER INDEX '||ix.index_owner||'.'||ix.index_name||
                            ' REBUILD SUBPARTITION '||ix.subpartition_name||' PARALLEL 16';
                        log_alert('AUTO-REBUILT '||ix.index_name||'/'||ix.subpartition_name);
                    EXCEPTION WHEN OTHERS THEN
                        log_alert('AUTO-REBUILD WARN '||ix.index_name||' '||SQLERRM);
                    END;
                END LOOP;
            END IF;

        EXCEPTION
            WHEN OTHERS THEN
                v_err := SUBSTRB(SQLERRM, 1, 4000);
                v_elapsed := ROUND(
                    EXTRACT(HOUR   FROM (SYSTIMESTAMP-v_step_start))*3600 +
                    EXTRACT(MINUTE FROM (SYSTIMESTAMP-v_step_start))*60   +
                    EXTRACT(SECOND FROM (SYSTIMESTAMP-v_step_start)), 1);
                UPDATE SYS.REORG_TRACKER
                   SET status       = 'FAILED',
                       completed_at = SYSTIMESTAMP,
                       elapsed_secs = v_elapsed,
                       error_msg    = v_err
                 WHERE schema_name = v_schema
                   AND table_name  = v_table
                   AND step_seq    = step.step_seq;
                COMMIT;
                log_alert('FAILED ['||step.step_seq||'] '||v_err);
                -- Do NOT raise - continue to next step
        END;

    END LOOP;

    log_alert('ALL STEPS PROCESSED for '||v_schema||'.'||v_table);

EXCEPTION
    WHEN OTHERS THEN
        v_err := SUBSTRB(SQLERRM, 1, 4000);
        log_alert('FATAL ERROR: '||v_err);
        RAISE;
END REORG_TABLE;
/
SET DEFINE ON
