CREATE OR REPLACE NONEDITIONABLE PROCEDURE auto_add_datafile_safe IS

  v_sql        VARCHAR2(2000);
  v_file_path  VARCHAR2(500);
  v_file_name  VARCHAR2(500);
  v_count      NUMBER;
  v_action     VARCHAR2(200);
  v_used_pct   NUMBER;
  v_add_file   BOOLEAN;

BEGIN

FOR ts IN (
    SELECT df.tablespace_name,
           MIN(df.file_name) base_file
    FROM dba_data_files df
    WHERE df.tablespace_name NOT LIKE 'TEMP%'
      AND df.tablespace_name NOT LIKE 'UNDOTBS%'
      AND df.tablespace_name NOT IN ('SYSTEM','SYSAUX')
    GROUP BY df.tablespace_name
) LOOP

    v_add_file := TRUE;

    /* Calculate tablespace usage */
    SELECT ROUND((SUM(df.bytes - NVL(fs.free_bytes,0)) / SUM(df.bytes))*100,2)
    INTO v_used_pct
    FROM dba_data_files df
    LEFT JOIN
        (SELECT file_id, SUM(bytes) free_bytes
         FROM dba_free_space
         GROUP BY file_id) fs
    ON df.file_id = fs.file_id
    WHERE df.tablespace_name = ts.tablespace_name;

    /* Check each file */
    FOR df_rec IN (
        SELECT file_id,
               file_name,
               bytes,
               autoextensible,
               maxbytes
        FROM dba_data_files
        WHERE tablespace_name = ts.tablespace_name
    ) LOOP

        DECLARE
            v_free_bytes NUMBER;
            v_file_used_pct NUMBER;
        BEGIN

            SELECT NVL(SUM(bytes),0)
            INTO v_free_bytes
            FROM dba_free_space
            WHERE file_id = df_rec.file_id;

            v_file_used_pct :=
               ROUND(((df_rec.bytes - v_free_bytes)/df_rec.bytes)*100,2);

            /* If any file still has space or can autoextend, skip */
            IF df_rec.autoextensible = 'YES'
               AND df_rec.bytes < df_rec.maxbytes
               AND df_rec.maxbytes <= TO_NUMBER(32) * 1024 * 1024 * 1024 THEN
                  v_add_file := FALSE;

            ELSIF v_file_used_pct < 90 THEN
                  v_add_file := FALSE;
            END IF;

        END;

    END LOOP;

    /* Add new file if required */
    IF v_add_file THEN

        BEGIN

            SELECT COUNT(*) + 1
            INTO v_count
            FROM dba_data_files
            WHERE tablespace_name = ts.tablespace_name;

            /* Extract directory path */
            v_file_path :=
               REGEXP_REPLACE(ts.base_file,'[\\/][^\\/]+$','');

            /* Create new filename */
            v_file_name :=
               v_file_path ||
               CASE WHEN INSTR(v_file_path,'\') > 0
                    THEN '\'
                    ELSE '/'
               END ||
               ts.tablespace_name || '_' ||
               LPAD(v_count,2,'0') || '.dbf';

            v_sql :=
            'ALTER TABLESPACE '||ts.tablespace_name||
            ' ADD DATAFILE '''||v_file_name||
            ''' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED';

            EXECUTE IMMEDIATE v_sql;

            v_action := 'Datafile added: '||v_file_name;

            INSERT INTO tablespace_log
            (tablespace_name, used_pct, action_time, action)
            VALUES
            (ts.tablespace_name, v_used_pct, SYSDATE, v_action);

            DBMS_OUTPUT.PUT_LINE(v_action);

        EXCEPTION
        WHEN OTHERS THEN

            v_action := 'FAILED: '||SQLERRM;

            INSERT INTO tablespace_log
            (tablespace_name, used_pct, action_time, action)
            VALUES
            (ts.tablespace_name, v_used_pct, SYSDATE, v_action);

        END;

    END IF;

END LOOP;

COMMIT;

END;
/



CREATE TABLE tablespace_log (
  log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  tablespace_name VARCHAR2(50),
  used_pct     NUMBER(5,2),
  action_time  DATE,
  action       VARCHAR2(100)
);


BEGIN
  DBMS_SCHEDULER.create_job (
    job_name        => 'AUTO_ADD_DATAFILE_JOB',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN auto_add_datafile; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=HOURLY; INTERVAL=1',
    enabled         => TRUE
  );
END;
/
